packages:
  - apps/*
  - packages/*
  - evals
  - evals/packages/*

allowBuilds:
  '@google/genai': false
  better-sqlite3: true
  electron-winstaller: false
  esbuild: true
  protobufjs: false

onlyBuiltDependencies:
  - better-sqlite3
  - electron
  - electron-winstaller
