import {
  AlertCircle,
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowUp,
  Bot,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  Circle,
  Clock3,
  ClipboardList,
  Copy,
  Command,
  Database,
  Eye,
  ExternalLink,
  File,
  FileOutput,
  Flag,
  Folder,
  FolderCog,
  FolderPlus,
  FolderKanban,
  Globe2,
  Inbox,
  Info,
  Keyboard,
  KeyRound,
  LayoutList,
  ListTodo,
  LockKeyhole,
  Menu,
  MoreHorizontal,
  PanelLeft,
  PanelRight,
  Palette,
  Paperclip,
  PencilLine,
  Play,
  Plus,
  RefreshCw,
  Search,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Square,
  SquarePen,
  Tag,
  Terminal,
  Trash2,
  Puzzle,
  WandSparkles,
  Workflow,
  X,
} from "lucide-react";
import type { LucideIcon, LucideProps } from "lucide-react";
import { cn } from "../../lib/utils.js";

const icons = {
  appearance: Palette,
  attention: CircleAlert,
  alert: AlertCircle,
  automation: Workflow,
  archive: Archive,
  "archive-restore": ArchiveRestore,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  back: ChevronLeft,
  browser: Globe2,
  models: Bot,
  check: Check,
  "check-circle": CheckCircle2,
  "chevron-down": ChevronDown,
  clock: Clock3,
  close: X,
  command: Command,
  copy: Copy,
  credentials: KeyRound,
  eye: Eye,
  external: ExternalLink,
  file: File,
  "file-output": FileOutput,
  flag: Flag,
  "folder-plus": FolderPlus,
  "folder-settings": FolderCog,
  "folder-kanban": FolderKanban,
  forward: ChevronRight,
  inbox: Inbox,
  info: Info,
  list: LayoutList,
  "list-todo": ListTodo,
  lock: LockKeyhole,
  menu: Menu,
  more: MoreHorizontal,
  panel: PanelLeft,
  "panel-right": PanelRight,
  paperclip: Paperclip,
  permissions: ShieldCheck,
  plan: ClipboardList,
  play: Play,
  plus: Plus,
  refresh: RefreshCw,
  rename: PencilLine,
  search: Search,
  settings: Settings,
  shortcuts: Keyboard,
  sliders: SlidersHorizontal,
  skills: Sparkles,
  source: Database,
  square: Square,
  "square-pen": SquarePen,
  status: Circle,
  stop: Square,
  tag: Tag,
  terminal: Terminal,
  trash: Trash2,
  extensions: Puzzle,
  wand: WandSparkles,
  workspace: Folder,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export interface IconProps extends Omit<LucideProps, "ref" | "size"> {
  name: IconName;
  size?: 14 | 16;
}

export function Icon({ name, className, size = 16, strokeWidth = 1.75, ...props }: IconProps) {
  const Glyph = icons[name];
  return (
    <Glyph
      aria-hidden="true"
      className={cn("ui-icon", className)}
      focusable="false"
      size={size}
      strokeWidth={strokeWidth}
      {...props}
    />
  );
}
